tap "fsouza/prettierd"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "junegunn/tap"
tap "mongodb/brew"
tap "unifiedplatform/tools", "git@github.int.midasplayer.com:UnifiedPlatform/homebrew-tools.git"
brew "argocd"
brew "asciinema"
brew "autoconf"
brew "automake"
brew "bash-completion"
brew "bat"
brew "bison"
brew "cairo"
brew "gdk-pixbuf"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "chafa"
brew "chruby"
brew "codespell"
brew "libyaml"
brew "cookiecutter"
brew "diff-so-fancy"
brew "fd"
brew "figlet"
brew "fnm"
brew "fzf"
brew "gdbm"
brew "gh"
brew "gofumpt"
brew "hadolint"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "libffi"
brew "ltex-ls"
brew "lua-language-server"
brew "node"
brew "markdownlint-cli"
brew "mas"
brew "minica"
brew "mongosh"
brew "tree-sitter"
brew "neovim"
brew "openssl@1.1"
brew "pnpm"
brew "postgresql@14"
brew "postgresql@15"
brew "pv"
brew "pyenv"
brew "python@3.11"
brew "python@3.8"
brew "ripgrep"
brew "ruby-install"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "terraform"
brew "the_silver_searcher"
brew "tldr"
brew "tree"
brew "wget"
brew "write-good"
brew "yarn"
brew "fsouza/prettierd/prettierd"
brew "junegunn/tap/blsd", args: ["HEAD"]
brew "mongodb/brew/mongodb-community"
brew "unifiedplatform/tools/kctl"
cask "font-hack-nerd-font"
cask "iterm2-beta"
cask "keycastr"
mas "Bitwarden", id: 1352778147
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Microsoft To Do", id: 1274495053
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Sequel Ace", id: 1518036000
mas "XGimp image editor", id: 1645334352
vscode "avetis.tokyo-night"
vscode "dbaeumer.vscode-eslint"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "ms-azuretools.vscode-docker"
vscode "ms-playwright.playwright"
vscode "ms-vscode-remote.remote-containers"
vscode "patbenatar.advanced-new-file"
vscode "vitest.explorer"
vscode "vscodevim.vim"
