#!/usr/bin/env bash
source $HOME/.profile

PATH="/usr/local/bin:$PATH"

# Added by install_latest_perl_osx.pl
[ -r $HOME/.bashrc ] && source $HOME/.bashrc

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
. "$HOME/.cargo/env"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Fix too many open files issue
ulimit -n 10240
