[manager]
prepend_keymap = [
  { on = "-", run = "leave", desc = "Go back to the parent directory" },
  # https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi
  { on = "l", run = "plugin smart-enter", desc = "Enter the child derectory, or open the file" },
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child derectory, or open the file" },
]
